alpha: 0.5
beta: 0
m: 0.5
s: 30

gpu_num: 2
epoch: 300

num_classes: 41
split_ratio: 0.95

batch_size: 128
lr: 0.0001

root_path: /home/Dataset/DCASE2020_Task2_dataset/dev_data
save_path: ./checkpoints/model.pth