alpha: 0.5
m: 0.5

gpu_num: 2
epoch: 300

num_classes: 41
split_ratio: 0.95

batch_size: 64

lr: 0.0001

save_path: ./checkpoints/model.pth

mode: noisy_arcmix # select one of ['arcface', 'arcmix', 'noisy_arcmix']